version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ap2user
      POSTGRES_PASSWORD: ap2pass
      POSTGRES_DB: ap2db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ap2user -d ap2db"]
      interval: 5s
      timeout: 5s
      retries: 10

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "50051:50051"
      - "8080:8080"      # HTTP REST (for Postman)
    environment:
      DB_URL: postgres://ap2user:ap2pass@postgres:5432/ap2db?sslmode=disable
      PAYMENT_ADDR: payment-service:50052
    depends_on:
      postgres:
        condition: service_healthy
      payment-service:
        condition: service_started

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "50052:50052"
    environment:
      DB_URL: postgres://ap2user:ap2pass@postgres:5432/ap2db?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      DB_URL: postgres://ap2user:ap2pass@postgres:5432/ap2db?sslmode=disable
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  rabbitmq_data:
  postgres_data:
